apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.4
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/infra/tailscale-operator/values.yaml
    - repoURL: https://github.com/jddemonteverde/homelab33.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jddemonteverde/homelab33.git
      targetRevision: main
      path: infra/tailscale-operator/secrets
    - repoURL: https://github.com/jddemonteverde/homelab33.git
      targetRevision: main
      path: infra/tailscale-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
