apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: ingress
  replicas: 2
  proxyClass: control-plane
